import Head from 'next/head'
import Link from 'next/link'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>



      <h1 className="text-3xl font-bold text-center">
        Home Page
      </h1>
      <Link href={'/products'}>go to products page</Link>

    </div>
  )
}
